// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2_AyG3_93fVRQnJfj68TPpO-3ysTF0yk',
    appId: '1:715167106654:web:d77677edb08084a12b56cf',
    messagingSenderId: '715167106654',
    projectId: 'plant-zone-2b9d0',
    authDomain: 'plant-zone-2b9d0.firebaseapp.com',
    storageBucket: 'plant-zone-2b9d0.firebasestorage.app',
    measurementId: 'G-ZVE2MR3M9Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVsaBXrbcOdj3JTcIyY9M10GpyAptjsTg',
    appId: '1:715167106654:android:9c8d2e647dd9ecb62b56cf',
    messagingSenderId: '715167106654',
    projectId: 'plant-zone-2b9d0',
    storageBucket: 'plant-zone-2b9d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUvLcZTvAEPv91MBHY8fc7b3hJkI5rPyY',
    appId: '1:715167106654:ios:5dc213e832e5f0ae2b56cf',
    messagingSenderId: '715167106654',
    projectId: 'plant-zone-2b9d0',
    storageBucket: 'plant-zone-2b9d0.firebasestorage.app',
    iosBundleId: 'com.example.plantzone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUvLcZTvAEPv91MBHY8fc7b3hJkI5rPyY',
    appId: '1:715167106654:ios:5dc213e832e5f0ae2b56cf',
    messagingSenderId: '715167106654',
    projectId: 'plant-zone-2b9d0',
    storageBucket: 'plant-zone-2b9d0.firebasestorage.app',
    iosBundleId: 'com.example.plantzone',
  );
}
